In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a[0][1:1]

array([2])

In [16]:
score_state = 6
scoremax = min(score_state - 2, 60 * 1)
values = np.ones(min(score_state - 2, 60 * 1) + 1)
prob_grid_normalscore = np.full((984,61),1/61)

prob_grid_normalscore[:,1:scoremax+1].dot(values[1:])+prob_grid_normalscore[:,0].dot(values[0])

array([0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196

In [17]:
5/61

0.08196721311475409

In [21]:
np.full((984,),2).dot(np.ones(1))

ValueError: shapes (984,) and (1,) not aligned: 984 (dim 0) != 1 (dim 0)

In [23]:
np.ones(1)[0].shape

()

In [45]:
import numpy as np

# 创建一个6x7的二维数组
score_state = 6
scoremax = min(score_state - 2, 60 * 1)
values = np.ones(min(score_state - 2, 60 * 1) + 1)

# 使用numpy的meshgrid函数来获取所有可能的索引组合
rows = np.meshgrid(range(values.shape[0]),indexing='ij')
np.array(range(values.shape))

TypeError: 'tuple' object cannot be interpreted as an integer

In [28]:
score_state=7
cols = score_state-cols-2


In [29]:
cols

array([[ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1]])

In [46]:
for u in range(0, min(score_state - 2, 60)):
    print(u)

0
1
2
3


In [50]:
V=np.ones((502,3,121))
print(V[3:1:-1,2,0].shape)
V[3:1:-1,2,0]


(2,)


array([1., 1.])

In [61]:
if np.all(np.abs(np.array([1,2,3]) - np.array([1.1,2.1,2.8])) < 0.15):
    print('yes')

In [68]:
a={1:1,2:2}
b={1:1,2:2}
b[1]=3
a=dict(b)
b[2]=9
print(a)
print(b)

{1: 3, 2: 2}
{1: 3, 2: 9}


In [71]:
s=9
values=np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64)
V = np.full((502, 3, 121), fill_value=np.nan)
V[s, 1, 0:len(values)] = values

In [73]:
V[s,1]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan])

In [ ]:
    for s in range(2, 502):
        values_old = {3: np.ones(min(s - 2, 60 * 0) + 1, dtype=np.float64),
                      2: np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64),
                      1: np.ones(min(s - 2, 60 * 2) + 1, dtype=np.float64)}
        values = {3: np.ones(min(s - 2, 60 * 0) + 1, dtype=np.float64),
                  2: np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64),
                  1: np.ones(min(s - 2, 60 * 2) + 1, dtype=np.float64)}

        for iter_index in range(iter_limit):
            for u in [0]:
                score_max = min(s - 2, 60)
                prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                          np.zeros(
                                                                                                              num_aiming_location, ))  # (984,)
                turn_to_thrownew = (prob_normalscore_0tosmax_dic.get(score_max).dot(values[2][u:u + score_max + 1])
                                    + prob_doublescore_dic.get(s, np.zeros(num_aiming_location, )) * 1
                                    + prob_bust.dot(1 + values[3][0]))
                values[3][u] = np.min(turn_to_thrownew)
                optimal_action_index[s, 2, u] = np.argmin(turn_to_thrownew)
            for u in range(0, min(s - 2, 60) + 1):
                score_max = min(s - u - 2, 60)
                prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                          np.zeros(
                                                                                                              num_aiming_location, ))  # (984,)
                turn_to_thrownew = (
                        prob_normalscore_0tosmax_dic.get(score_max).dot(values[1][u:u + score_max + 1])
                        + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                        + prob_bust.dot(1 + values[3][0])
                )
                values[2][u] = np.min(turn_to_thrownew)
                optimal_action_index[s, 1, u] = np.argmin(turn_to_thrownew)
            for u in range(1, min(s - 2, 120) + 1):
                score_max = min(s - u - 2, 60)
                prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                          np.zeros(
                                                                                                              num_aiming_location, ))  # (984,)
                turn_to_thrownew = (
                        prob_normalscore_0tosmax_dic.get(score_max).dot(1 + V[s - u:s - u - score_max - 1:-1, 2, 0])
                        + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                        + prob_bust.dot(1 + values[3][0])
                )
                values[1][u] = np.min(turn_to_thrownew)
                optimal_action_index[s, 0, u] = np.argmin(turn_to_thrownew)

            for u in [0]:
                score_max = min(s - u - 2, 60)
                prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                          np.zeros(
                                                                                                              num_aiming_location, ))  # (984,)
                turn_to_thrownew = (
                    prob_grid_normalscore[:, 0].dot(1 + values[3][0])
                    + np.array(prob_grid_normalscore[:, 1:score_max + 1]).dot(
                        1 + V[s - u - 1:s - u - score_max - 1:-1, 2, 0])
                    + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                    + prob_bust.dot(1 + values[3][0])
                )
                values[1][u] = np.min(turn_to_thrownew)
                optimal_action_index[s, 0, u] = np.argmin(turn_to_thrownew)

            jump_out_of_iter = True
            for remaining_throws in [1, 2, 3]:
                if not np.all(np.abs(values_old[remaining_throws] - values[remaining_throws]) < iter_error):
                    jump_out_of_iter = False
                    break
            if not jump_out_of_iter:
                values_old = copy.deepcopy(values)
            else:
                break