In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a[0][1:1]

array([2])

In [16]:
score_state = 6
scoremax = min(score_state - 2, 60 * 1)
values = np.ones(min(score_state - 2, 60 * 1) + 1)
prob_grid_normalscore = np.full((984,61),1/61)

prob_grid_normalscore[:,1:scoremax+1].dot(values[1:])+prob_grid_normalscore[:,0].dot(values[0])

array([0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196721,
       0.08196721, 0.08196721, 0.08196721, 0.08196721, 0.08196

In [17]:
5/61

0.08196721311475409

In [21]:
np.full((984,),2).dot(np.ones(1))

ValueError: shapes (984,) and (1,) not aligned: 984 (dim 0) != 1 (dim 0)

In [23]:
np.ones(1)[0].shape

()

In [45]:
import numpy as np

# 创建一个6x7的二维数组
score_state = 6
scoremax = min(score_state - 2, 60 * 1)
values = np.ones(min(score_state - 2, 60 * 1) + 1)

# 使用numpy的meshgrid函数来获取所有可能的索引组合
rows = np.meshgrid(range(values.shape[0]),indexing='ij')
np.array(range(values.shape))

TypeError: 'tuple' object cannot be interpreted as an integer

In [28]:
score_state=7
cols = score_state-cols-2


In [29]:
cols

array([[ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 5,  4,  3,  2,  1,  0, -1]])

In [46]:
for u in range(0, min(score_state - 2, 60)):
    print(u)

0
1
2
3


In [50]:
V=np.ones((502,3,121))
print(V[3:1:-1,2,0].shape)
V[3:1:-1,2,0]


(2,)


array([1., 1.])

In [61]:
if np.all(np.abs(np.array([1,2,3]) - np.array([1.1,2.1,2.8])) < 0.15):
    print('yes')

In [68]:
a={1:1,2:2}
b={1:1,2:2}
b[1]=3
a=dict(b)
b[2]=9
print(a)
print(b)

{1: 3, 2: 2}
{1: 3, 2: 9}


In [71]:
s=9
values=np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64)
V = np.full((502, 3, 121), fill_value=np.nan)
V[s, 1, 0:len(values)] = values

In [73]:
V[s,1]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan])

In [1]:
import numpy as np
import function_get_aiming_grid
import function_board as fb
playerID = 7
name_pa = 'player{}'.format(playerID)
[aiming_grid, prob_grid_normalscore, prob_grid_singlescore, prob_grid_doublescore, prob_grid_triplescore,
 prob_grid_bullscore] = function_get_aiming_grid.load_aiming_grid(name_pa)
num_aiming_location = aiming_grid.shape[0]
prob_normalscore_0tosmax_dic = {}
prob_normalscore_0tosmaxsum_dic = {}
for score_max in range(0, 61):
    score_max_plus1 = score_max + 1
    prob_normalscore_0tosmax_dic[score_max] = np.array(prob_grid_normalscore[:, 0:score_max_plus1])
    prob_normalscore_0tosmaxsum_dic[score_max] = prob_normalscore_0tosmax_dic[score_max].sum(axis=1)

prob_doublescore_dic = {}
for doublescore_index in range(20):
    doublescore = 2 * (doublescore_index + 1)
    prob_doublescore_dic[doublescore] = np.array(prob_grid_doublescore[:, doublescore_index])
prob_doublescore_dic[fb.score_DB] = np.array(prob_grid_bullscore[:, 1])

# Initialize the value function for all states (s, i, u)
V = np.full((502, 3, 121), fill_value=np.nan)
optimal_action_index = np.full((502, 3, 121), fill_value=-1,dtype=np.int16)
V[0, :, 0] = 0  # If the score is 0, the game is finished
V[1, :, 0] = np.inf
optimal_action_index[0:2, :, 0] = -999
    

load_pickle from ../../data_parameter/player_gaussin_fit/grid_v2/player7_gaussin_prob_grid_v2.pkl


In [2]:
import copy
num_aiming_location = aiming_grid.shape[0]
prob_normalscore_0tosmax_dic = {}
prob_normalscore_0tosmaxsum_dic = {}
for score_max in range(0, 61):
    score_max_plus1 = score_max + 1
    prob_normalscore_0tosmax_dic[score_max] = np.array(prob_grid_normalscore[:, 0:score_max_plus1])
    prob_normalscore_0tosmaxsum_dic[score_max] = prob_normalscore_0tosmax_dic[score_max].sum(axis=1)

prob_doublescore_dic = {}
for doublescore_index in range(20):
    doublescore = 2 * (doublescore_index + 1)
    prob_doublescore_dic[doublescore] = np.array(prob_grid_doublescore[:, doublescore_index])
prob_doublescore_dic[fb.score_DB] = np.array(prob_grid_bullscore[:, 1])

# Initialize the value function for all states (s, i, u)
V = np.full((502, 3, 121), fill_value=np.nan)
optimal_action_index = np.full((502, 3, 121), fill_value=-1,dtype=np.int16)
V[0, :, 0] = 0  # If the score is 0, the game is finished
V[1, :, 0] = np.inf
optimal_action_index[0:2, :, 0] = -999

iter_limit = 1000
iter_error = 0.0001
for s in range(2, 10):
    values_old = {3: np.ones(min(s - 2, 60 * 0) + 1, dtype=np.float64),
                  2: np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64),
                  1: np.ones(min(s - 2, 60 * 2) + 1, dtype=np.float64)}
    values = {3: np.ones(min(s - 2, 60 * 0) + 1, dtype=np.float64),
              2: np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64),
              1: np.ones(min(s - 2, 60 * 2) + 1, dtype=np.float64)}

    for iter_index in range(iter_limit):
        for u in [0]:
            score_max = min(s - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (prob_normalscore_0tosmax_dic.get(score_max).dot(values[2][u:u + score_max + 1])
                                + prob_doublescore_dic.get(s, np.zeros(num_aiming_location, )) * 1
                                + prob_bust.dot(1 + values[3][0]))
            values[3][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 2, u] = np.argmin(turn_to_thrownew)
        for u in range(0, min(s - 2, 60) + 1):
            score_max = min(s - u - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (
                    prob_normalscore_0tosmax_dic.get(score_max).dot(values[1][u:u + score_max + 1])
                    + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                    + prob_bust.dot(1 + values[3][0])
            )
            values[2][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 1, u] = np.argmin(turn_to_thrownew)
        for u in range(1, min(s - 2, 120) + 1):
            score_max = min(s - u - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (
                    prob_normalscore_0tosmax_dic.get(score_max).dot(1 + V[s - u:s - u - score_max - 1:-1, 2, 0])
                    + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                    + prob_bust.dot(1 + values[3][0])
            )
            values[1][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 0, u] = np.argmin(turn_to_thrownew)

        for u in [0]:
            score_max = min(s - u - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (
                prob_grid_normalscore[:, 0].dot(1 + values[3][0])
                + np.array(prob_grid_normalscore[:, 1:score_max + 1]).dot(
                    1 + V[s - u - 1:s - u - score_max - 1:-1, 2, 0])
                + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                + prob_bust.dot(1 + values[3][0])
            )
            values[1][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 0, u] = np.argmin(turn_to_thrownew)

        jump_out_of_iter = True
        for remaining_throws in [1, 2, 3]:
            if not np.all(np.abs(values_old[remaining_throws] - values[remaining_throws]) < iter_error):
                jump_out_of_iter = False
                break
        if not jump_out_of_iter:
            values_old = copy.deepcopy(values)
        else:
            break

    V[s, 2, 0] = values[3][0]
    V[s, 1, :len(values[2])] = values[2]
    V[s, 0, :len(values[1])] = values[1]
    print(f"\rscore_state = {s} finished.",end="")

score_state = 9 finished.

In [ ]:
import copy
num_aiming_location = aiming_grid.shape[0]
prob_normalscore_0tosmax_dic = {}
prob_normalscore_0tosmaxsum_dic = {}
for score_max in range(0, 61):
    score_max_plus1 = score_max + 1
    prob_normalscore_0tosmax_dic[score_max] = np.array(prob_grid_normalscore[:, 0:score_max_plus1])
    prob_normalscore_0tosmaxsum_dic[score_max] = prob_normalscore_0tosmax_dic[score_max].sum(axis=1)

prob_doublescore_dic = {}
for doublescore_index in range(20):
    doublescore = 2 * (doublescore_index + 1)
    prob_doublescore_dic[doublescore] = np.array(prob_grid_doublescore[:, doublescore_index])
prob_doublescore_dic[fb.score_DB] = np.array(prob_grid_bullscore[:, 1])

# Initialize the value function for all states (s, i, u)
V = np.full((502, 3, 121), fill_value=np.nan)
optimal_action_index = np.full((502, 3, 121), fill_value=-1,dtype=np.int16)
V[0, :, 0] = 0  # If the score is 0, the game is finished
V[1, :, 0] = np.inf
optimal_action_index[0:2, :, 0] = -999

iter_limit = 1000
iter_error = 0.0001
for s in range(2, 10):
    values_old = {3: np.ones(min(s - 2, 60 * 0) + 1, dtype=np.float64),
                  2: np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64),
                  1: np.ones(min(s - 2, 60 * 2) + 1, dtype=np.float64)}
    values = {3: np.ones(min(s - 2, 60 * 0) + 1, dtype=np.float64),
              2: np.ones(min(s - 2, 60 * 1) + 1, dtype=np.float64),
              1: np.ones(min(s - 2, 60 * 2) + 1, dtype=np.float64)}

    for iter_index in range(iter_limit):
        for u in [0]:
            score_max = min(s - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (prob_normalscore_0tosmax_dic.get(score_max).dot(values[2][u:u + score_max + 1])
                                + prob_doublescore_dic.get(s, np.zeros(num_aiming_location, )) * 1
                                + prob_bust.dot(1 + values[3][0]))
            values[3][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 2, u] = np.argmin(turn_to_thrownew)
            
        u_range = np.arange(0, min(s - 2, 60) + 1)
        score_max_vector = np.minimum(s - u_range - 2, 60)
        prob_bust_matrix = 1 - prob_normalscore_0tosmaxsum_dic[score_max_vector[:, None]] - prob_doublescore_dic.get(s - u_range[:, None], np.zeros((len(u_range), num_aiming_location)))
        turn_to_thrownew_matrix = (
    np.dot(prob_normalscore_0tosmax_dic.get(score_max), values[1][None, :]) + 
    prob_doublescore_dic.get(s - u_range[:, None], np.zeros((len(u_range), num_aiming_location))) * 1 + 
    prob_bust_matrix.dot(1 + values[3][0])
)
        for u in range(0, min(s - 2, 60) + 1):
            score_max = min(s - u - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (
                    prob_normalscore_0tosmax_dic.get(score_max).dot(values[1][u:u + score_max + 1])
                    + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                    + prob_bust.dot(1 + values[3][0])
            )
            values[2][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 1, u] = np.argmin(turn_to_thrownew)
            
            
            
        for u in range(1, min(s - 2, 120) + 1):
            score_max = min(s - u - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (
                    prob_normalscore_0tosmax_dic.get(score_max).dot(1 + V[s - u:s - u - score_max - 1:-1, 2, 0])
                    + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                    + prob_bust.dot(1 + values[3][0])
            )
            values[1][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 0, u] = np.argmin(turn_to_thrownew)

        for u in [0]:
            score_max = min(s - u - 2, 60)
            prob_bust = 1 - prob_normalscore_0tosmaxsum_dic.get(score_max) - prob_doublescore_dic.get(s - u,
                                                                                                      np.zeros(
                                                                                                          num_aiming_location, ))  # (984,)
            turn_to_thrownew = (
                prob_grid_normalscore[:, 0].dot(1 + values[3][0])
                + np.array(prob_grid_normalscore[:, 1:score_max + 1]).dot(
                    1 + V[s - u - 1:s - u - score_max - 1:-1, 2, 0])
                + prob_doublescore_dic.get(s - u, np.zeros(num_aiming_location, )) * 1
                + prob_bust.dot(1 + values[3][0])
            )
            values[1][u] = np.min(turn_to_thrownew)
            optimal_action_index[s, 0, u] = np.argmin(turn_to_thrownew)

        jump_out_of_iter = True
        for remaining_throws in [1, 2, 3]:
            if not np.all(np.abs(values_old[remaining_throws] - values[remaining_throws]) < iter_error):
                jump_out_of_iter = False
                break
        if not jump_out_of_iter:
            values_old = copy.deepcopy(values)
        else:
            break

    V[s, 2, 0] = values[3][0]
    V[s, 1, :len(values[2])] = values[2]
    V[s, 0, :len(values[1])] = values[1]
    print(f"\rscore_state = {s} finished.",end="")

In [10]:

def solve_dp_noturn_valueiteration(aiming_grid, prob_grid_normalscore, prob_grid_doublescore=None,prob_grid_bullscore=None, prob_grid_doublescore_dic=None):
    ## aiming_grid
    num_aiming_location = aiming_grid.shape[0]
    prob_normalscore_1tosmax_dic = {}
    prob_normalscore_1tosmaxsum_dic = {}
    for score_max in range(0, 61):
        score_max_plus1 = score_max + 1
        prob_normalscore_1tosmax_dic[score_max] = np.array(prob_grid_normalscore[:, 0:score_max_plus1])
        prob_normalscore_1tosmaxsum_dic[score_max] = prob_normalscore_1tosmax_dic[score_max].sum(axis=1)
    if prob_grid_doublescore_dic is None:
        prob_doublescore_dic = {}
        for doublescore_index in range(20):
            doublescore = 2 * (doublescore_index + 1)
            prob_doublescore_dic[doublescore] = np.array(prob_grid_doublescore[:, doublescore_index])
    else:
        prob_doublescore_dic = prob_grid_doublescore_dic
    prob_DB = np.array(prob_grid_bullscore[:, 1])

    ##
    optimal_value = np.zeros((502, 3, 121),dtype=np.float32)
    optimal_action_index = np.zeros((502, 3, 121), dtype=np.float32)
    optimal_action_index[0,:,:] = -1
    optimal_action_index[1,:,:] = -1

    iter_limit = 1000
    iter_error = 0.0001

    for score_state in range(2,10):
    ## solve successively for s = 2,...,501
        for iter_index in range(iter_limit):

            # i=1
            diff_1=0
            for u in range(0, min(120, score_state - 2)+1):
                score_max = min(score_state - u - 2, 60)
                score_max_plus1 = score_max + 1
                num_tothrow= prob_normalscore_1tosmax_dic[score_max].dot(optimal_value[score_state - u: score_state - u - score_max-1:-1, 2, 0])
                num_tothrow +=prob_normalscore_1tosmaxsum_dic[score_max]
                prob_bust = 1 - prob_normalscore_1tosmaxsum_dic[score_max]
                if (score_state-u == fb.score_DB):
                    num_tothrow=num_tothrow+prob_DB*1
                    prob_bust -= prob_DB
                elif (score_state-u <= 40 and (score_state-u) % 2 == 0):
                    num_tothrow = num_tothrow+ prob_doublescore_dic[score_state-u] * 1
                    prob_bust -= prob_doublescore_dic[score_state-u]
                else:
                    pass

                num_tothrow_new=num_tothrow + prob_bust * (1+optimal_value[score_state,2,0])
                num_tothrow_value_new=np.min(num_tothrow_new)
                diff_1=np.abs(num_tothrow_value_new-optimal_value[score_state,0,u])
                optimal_value[score_state, 0, u]=num_tothrow_value_new
                optimal_action_index[score_state, 0, u] = num_tothrow_new.argmin()

            #i=2
            diff_2=0
            for u in range(0, min(60, score_state - 2)+1):
                score_max = min(score_state - u - 2, 60)
                score_max_plus1 = score_max + 1
                num_tothrow = prob_normalscore_1tosmax_dic[score_max].dot(optimal_value[score_state,0,u:u+score_max+1])
                prob_bust = 1 - prob_normalscore_1tosmaxsum_dic[score_max]
                if (score_state - u == fb.score_DB):
                    num_tothrow = num_tothrow+ prob_DB * 1
                    prob_bust -= prob_DB
                elif (score_state - u <= 40 and (score_state - u) % 2 == 0):
                    num_tothrow = num_tothrow+ prob_doublescore_dic[score_state-u] * 1
                    prob_bust -= prob_doublescore_dic[score_state-u]
                else:
                    pass
                num_tothrow_new = num_tothrow + prob_bust * (1 + optimal_value[score_state, 2, 0])
                num_tothrow_value_new = np.min(num_tothrow_new)
                diff_2 = np.abs(num_tothrow_value_new - optimal_value[score_state, 1,u])
                optimal_value[score_state, 1, u] = num_tothrow_value_new
                optimal_action_index[score_state, 1, u] = num_tothrow_new.argmin()

            #i=3
            u = 0
            diff_3=0
            score_max = min(score_state - 2, 60)
            num_tothrow= prob_normalscore_1tosmax_dic[score_max].dot(optimal_value[score_state,1,0:score_max+1])
            prob_bust = 1 - prob_normalscore_1tosmaxsum_dic[score_max]
            if (score_state - u == fb.score_DB):
                num_tothrow = num_tothrow+ prob_DB * 1
                prob_bust -= prob_DB
            elif (score_state - u <= 40 and score_state % 2 == 0):
                num_tothrow= num_tothrow+ prob_doublescore_dic[score_state] * 1
                prob_bust -= prob_doublescore_dic[score_state]
            else:
                pass
            num_tothrow_new = num_tothrow + prob_bust * (1 + optimal_value[score_state, 2, 0])
            num_tothrow_value_new = np.min(num_tothrow_new)
            diff_3 = np.abs(num_tothrow_value_new - optimal_value[score_state, 2, u])
            optimal_value[score_state, 2, u] = num_tothrow_value_new
            optimal_action_index[score_state, 2, u] = num_tothrow_new.argmin()

            if np.any([diff_1,diff_2,diff_3])<iter_error:
                break
        print(score_state)
    return [optimal_value, optimal_action_index]


playerID = 7
name_pa = 'player{}'.format(playerID)
[aiming_grid, prob_grid_normalscore, prob_grid_singlescore, prob_grid_doublescore, prob_grid_triplescore,
 prob_grid_bullscore] = function_get_aiming_grid.load_aiming_grid(name_pa)
result = solve_dp_noturn_valueiteration(aiming_grid, prob_grid_normalscore, prob_grid_doublescore,prob_grid_bullscore)

load_pickle from ../../data_parameter/player_gaussin_fit/grid_v2/player7_gaussin_prob_grid_v2.pkl
2
3
4
5
6
7
8
9
